version: '3.7'

services:
    database:
        image: 'mongo'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: sprint-retrospective
            MONGO_DATA_DIR: /var/lib/mongodb
        volumes:
            - data-mongo:/var/lib/mongodb
        restart: always

    redis:
        image: 'redis'
        restart: always
        ports:
            - "6379"

    api:
        build: https://github.com/RobinJ1995/sprint-retrospective-server.git
        image: robinj/sprintretrospective-api
        ports:
            - 5432:5432
        environment:
            DB_HOST: 'database'
            REDIS_URL: 'redis://redis'
            REDIS_PUBSUB_TOPIC: 'updates'
            WEBSOCKET_PUBLIC_BASE_URL: 'ws://localhost:5433/'
            PORT: 5432
            ADMIN_KEY: 'i_am_root'
        depends_on:
            - database
            - redis
            - websocket
        restart: always

    websocket:
        build: .
        image: robinj/sprintretrospective-websocket-server
        ports:
            - 5433:5433
        environment:
            REDIS_URL: 'redis://redis'
            REDIS_PUBSUB_TOPIC: 'updates'
            PORT: 5433
            PING_INTERVAL_MS: 5000
        depends_on:
            - redis
        restart: always

    frontend:
        build:
            context: https://github.com/RobinJ1995/sprint-retrospective.git
            args:
                API_ENDPOINT: 'http://localhost:5432'
        image: robinj/sprintretrospective-frontend
        ports:
            - 5431:80
        depends_on:
            - api
        restart: always

volumes:
    data-mongo:
